FROM ghcr.io/open-webui/open-webui:main

# Connector dependencies
RUN pip install --no-cache-dir \
    simple-salesforce \
    pysnow \
    azure-data-tables \
    azure-storage-blob \
    google-api-python-client \
    google-auth \
    google-auth-httplib2 \
    google-auth-oauthlib \
    httpx \
    requests
